window.SCENE_TABLES = {
  "Campaign": {
    "Backstory Prompt": [
      "A routine contract concealed a territorial claim.",
      "A rescue mission revealed a colony that should not exist.",
      "A corporate audit exposed sabotage in a frontier supply chain.",
      "A survey team found evidence of an earlier, erased expedition.",
      "A colonial dispute became personal when someone vanished.",
      "A trusted patron funded the mission with stolen capital.",
      "An old war crime resurfaced in a remote company town.",
      "A settlement prosperity depends on an illegal secret.",
      "A frontier marshal inherits a case nobody wants reopened.",
      "A trade route collapsed after ships began returning empty."
    ],
    "Inciting Incident": [
      "A distress call arrives from a place officially abandoned.",
      "A local authority asks for help but refuses to give full access.",
      "A cargo container is opened and the manifest is impossible.",
      "A worker riot blocks the only safe route off-world.",
      "A rival crew reaches the site minutes before the protagonists.",
      "A habitat system begins failing in a way that looks intentional.",
      "A fugitive offers proof of a hidden corporate program.",
      "A survey drone returns with nonhuman biological traces.",
      "A debt marker is called in at the worst possible time.",
      "A quarantine order is issued after the crew is already inside."
    ],
    "Campaign Tone": [
      "Hard industrial survival with moral compromise.",
      "Frontier lawkeeping under corporate pressure.",
      "Exploration, salvage, and slow-burn horror.",
      "Merchant crew caught between factions.",
      "Colonial mystery with military consequences.",
      "Blue-collar workers against remote management.",
      "Scientific discovery with escalating containment failure.",
      "Sparse western frontier in a hostile star sector.",
      "Dirty politics, logistics, and personal loyalties.",
      "Resource extraction drama with alien unknowns."
    ],
    "Sector Trouble": [
      "Fuel shortages make every jump political.",
      "A megacorp is quietly buying failed colonies.",
      "Colonial militias are forming around disputed claims.",
      "Pirates have begun using military-grade codes.",
      "A biological outbreak is being hidden to protect profits.",
      "A new route bypasses an old power center.",
      "Survey charts are unreliable near a strange stellar object.",
      "A labor movement has spread across multiple facilities.",
      "Terraforming failures are forcing evacuations.",
      "Independent traders are squeezed by bonded contracts."
    ]
  },
  "Core Oracles": {
    "Action": [
      "Secure",
      "Reveal",
      "Betray",
      "Evacuate",
      "Track",
      "Extract",
      "Negotiate",
      "Sabotage",
      "Contain",
      "Survey",
      "Exploit",
      "Protect",
      "Mislead",
      "Repair",
      "Interrogate",
      "Transport",
      "Fortify",
      "Investigate",
      "Seize",
      "Delay"
    ],
    "Theme": [
      "Debt",
      "Isolation",
      "Contamination",
      "Authority",
      "Scarcity",
      "Loyalty",
      "Decay",
      "Discovery",
      "Profit",
      "Survival",
      "Obedience",
      "Rebellion",
      "Inheritance",
      "Fear",
      "Duty",
      "Memory",
      "Identity",
      "Exposure",
      "Compromise",
      "Control"
    ],
    "Descriptor": [
      "corroded",
      "sterile",
      "overcrowded",
      "abandoned",
      "sealed",
      "floodlit",
      "jury-rigged",
      "luxurious",
      "claustrophobic",
      "exposed",
      "obsolete",
      "militarized",
      "contaminated",
      "remote",
      "ceremonial",
      "half-built",
      "frozen",
      "humid",
      "dust-choked",
      "watched"
    ],
    "Focus": [
      "airlock",
      "terminal",
      "worker",
      "contract",
      "cargo",
      "beacon",
      "map",
      "weapon",
      "specimen",
      "ledger",
      "medbay",
      "reactor",
      "dock",
      "hab block",
      "mine shaft",
      "ruin",
      "storm wall",
      "security team",
      "sensor mast",
      "lifeboat"
    ]
  },
  "Space Encounters": {
    "Space Sighting": [
      "a silent ore hauler tumbling without running lights",
      "a patrol frigate holding position near a dark moon",
      "a debris ring with fresh impact flashes",
      "a fuel tender broadcasting an outdated company code",
      "an automated buoy warning ships away from open space",
      "a shuttle burning hard with no transponder",
      "a station module venting atmosphere in short pulses",
      "a cluster of mining drones moving in formation",
      "a derelict lifeboat with its hatch sealed from outside",
      "an ice comet cut by industrial bore marks"
    ],
    "Spaceborne Peril": [
      "micrometeorite storm crossing the flight path",
      "false transponder leading into an ambush envelope",
      "reactor bleed from a damaged nearby vessel",
      "navigation ghost caused by gravitational shear",
      "corporate interdiction order with unclear authority",
      "debris field masking live ordnance",
      "boarding drone attached to the hull",
      "life support reserve consumed faster than expected",
      "radiation surge from local stellar activity",
      "quarantine beacon that activates after approach"
    ],
    "Spaceborne Opportunity": [
      "salvage rights to an unclaimed cargo pod",
      "a stranded crew with valuable local knowledge",
      "an old survey cache with partial route data",
      "a hidden refuel point known only to independents",
      "a wreck containing spare parts for a damaged system",
      "a merchant convoy willing to pay for escort",
      "an illegal transmitter revealing faction traffic",
      "a scientific anomaly worth a patron bonus",
      "a customs loophole before a checkpoint updates",
      "a rescue claim that can build reputation"
    ],
    "Starship Mission": [
      "emergency extraction",
      "cargo transfer",
      "system survey",
      "patrol intercept",
      "medical evacuation",
      "quiet smuggling run",
      "corporate courier route",
      "debris salvage",
      "colony resupply",
      "search and rescue"
    ]
  },
  "Planets": {
    "Planetary Class": [
      "airless rock",
      "thin-atmosphere mining world",
      "cold desert colony",
      "humid jungle world",
      "oceanic archipelago",
      "tainted atmosphere world",
      "ice-locked moon",
      "volcanic furnace world",
      "terraformed garden colony",
      "jovian orbital zone",
      "asteroid belt",
      "stable comet"
    ],
    "Planet Traits": [
      "unstable weather windows",
      "scarce surface water",
      "valuable deep-crust minerals",
      "old failed terraforming grid",
      "dangerous native biosphere",
      "corporate monopoly infrastructure",
      "fragmented colonial governance",
      "unreliable orbital comms",
      "large uncharted exclusion zone",
      "seasonal migration hazards"
    ],
    "Planetside Peril": [
      "toxic storm front",
      "sinkhole into industrial caverns",
      "territorial alien fauna",
      "corrosive fog",
      "terraformer malfunction",
      "armed claim jumpers",
      "heat bloom visible to predators",
      "unstable ice shelf",
      "flooded tunnel network",
      "security cordon around a secret site"
    ],
    "Planetside Opportunity": [
      "rare mineral vein",
      "surviving pre-collapse equipment",
      "friendly local guide",
      "hidden water source",
      "shortcut through a survey tunnel",
      "abandoned field lab",
      "salvageable rover",
      "black-market landing zone",
      "evidence of a missing team",
      "natural shelter against the storm"
    ]
  },
  "Settlements": {
    "Settlement Type": [
      "company town",
      "mining camp",
      "research base",
      "terraforming colony",
      "free trader port",
      "penal labor camp",
      "frontier homestead cluster",
      "orbital transfer station",
      "military depot",
      "refugee habitat"
    ],
    "First Look": [
      "stacked prefab modules under harsh lights",
      "a single pressurized street filled with red dust",
      "security cameras at every pressure door",
      "workers moving silently between shifts",
      "corporate slogans painted over older warnings",
      "a chapel, bar, and medbay sharing one module",
      "patched hull plates and mismatched air recyclers",
      "children watching strangers from sealed windows",
      "an unfinished landing pad half-buried in grit",
      "armed guards pretending not to be nervous"
    ],
    "Authority": [
      "company administrator",
      "elected colonial council",
      "military commander",
      "labor foreman coalition",
      "religious founder",
      "criminal broker",
      "scientific director",
      "AI logistics system",
      "marshal office",
      "family patriarch or matriarch"
    ],
    "Settlement Trouble": [
      "rations are being diverted",
      "a strike is near violence",
      "the water plant is failing",
      "the official population count is false",
      "a missing child is blamed on outsiders",
      "security has started disappearing people",
      "the colony charter is contested",
      "a disease is being hidden",
      "two factions control different life support systems",
      "a local taboo blocks the obvious solution"
    ],
    "Settlement Project": [
      "expand the pressure dome",
      "repair the orbital beacon",
      "open a new mine face",
      "complete a terraforming tower",
      "build militia defenses",
      "restore the hospital",
      "install a fusion backup",
      "survey a nearby ruin",
      "negotiate an off-world contract",
      "purge contamination from the water system"
    ]
  },
  "Districts": {
    "Access": {
      "First Look": [
        "hardened checkpoint with worn blast shutters",
        "cargo gates lined with inspection drones",
        "arrival concourse packed with delayed workers",
        "customs booth running on emergency power",
        "pressure locks cycling too slowly",
        "landing tunnel scored by old fire"
      ],
      "Complication": [
        "entry papers do not match the current authority",
        "the route is sealed until a bribe is paid",
        "a wanted face appears on the checkpoint display",
        "an alarm traps everyone between doors",
        "cargo scanners detect something no one packed",
        "a rival crew arrives with higher priority clearance"
      ],
      "Useful Detail": [
        "maintenance bypass",
        "sympathetic customs clerk",
        "forgotten service elevator",
        "blind spot in the camera grid",
        "old paper logbook",
        "loose floor panel hiding contraband"
      ]
    },
    "Community": {
      "First Look": [
        "crowded canteen with improvised shrine",
        "schoolroom doubling as ration office",
        "public notice wall layered with grievances",
        "communal laundry near a pressure bulkhead",
        "recreation room lit by flickering screens",
        "market stalls built from shipping crates"
      ],
      "Complication": [
        "locals refuse to speak while security is present",
        "a rumor spreads faster than facts",
        "a family feud blocks cooperation",
        "a public argument becomes a loyalty test",
        "someone asks for rescue before information",
        "children know the truth adults avoid"
      ],
      "Useful Detail": [
        "old-timer with route knowledge",
        "community radio channel",
        "black-market cook",
        "memorial list of missing workers",
        "hidden prayer room",
        "worker grievance ledger"
      ]
    },
    "Engineering": {
      "First Look": [
        "vibration through grated floors",
        "pipes sweating chemical frost",
        "warning lights under a film of dust",
        "reactor access behind patched insulation",
        "coolant dripping into collection buckets",
        "manual controls polished by constant use"
      ],
      "Complication": [
        "repairs require shutting down life support elsewhere",
        "a system has been deliberately miscalibrated",
        "the only engineer is missing",
        "a bypass works but will burn out soon",
        "a damaged drone guards the wrong room",
        "pressure loss begins during the inspection"
      ],
      "Useful Detail": [
        "spare regulator",
        "handwritten repair map",
        "open diagnostic port",
        "service crawlway",
        "faulty sensor loop",
        "power cell with one good charge"
      ]
    },
    "Living": {
      "First Look": [
        "stacked bunks behind thin privacy curtains",
        "family habs decorated with Earth memorabilia",
        "sleep pods lining a narrow corridor",
        "condensation on every wall panel",
        "personal lockers chained shut",
        "a quiet room that feels recently abandoned"
      ],
      "Complication": [
        "someone has searched the rooms before you",
        "a hidden occupant refuses to leave",
        "private evidence implicates a public hero",
        "a quarantine mark is painted inside",
        "a domestic dispute reveals faction pressure",
        "an air vent carries voices from a sealed room"
      ],
      "Useful Detail": [
        "personal diary",
        "stashed keycard",
        "contraband radio",
        "family photo with a clue",
        "medication label",
        "map scratched under a bunk"
      ]
    },
    "Medical": {
      "First Look": [
        "triage beds divided by plastic curtains",
        "autodoc with a cracked display",
        "chemical smell beneath disinfectant",
        "cold storage with missing inventory",
        "overworked medic refusing sleep",
        "biohazard signs covered by tape"
      ],
      "Complication": [
        "records are locked by corporate legal order",
        "a patient recognizes the crew",
        "samples have been switched",
        "the medic is treating both sides",
        "a body is listed as discharged",
        "symptoms do not match any known pathogen"
      ],
      "Useful Detail": [
        "bloodwork anomaly",
        "encrypted patient file",
        "hidden vaccine cache",
        "medical waste route",
        "sedative injector",
        "morgue access tag"
      ]
    },
    "Operations": {
      "First Look": [
        "mission screens showing outdated maps",
        "dispatch desks under emergency lighting",
        "comms operators speaking in code",
        "a wall of status boards and red flags",
        "locked glass office overlooking the floor",
        "archive cabinets beside a dead printer"
      ],
      "Complication": [
        "the logs were edited minutes ago",
        "a superior gives contradictory orders",
        "an emergency channel opens from a forbidden site",
        "the map omits a whole sector",
        "dispatch records show an impossible trip",
        "a clerk begs you not to mention their name"
      ],
      "Useful Detail": [
        "shift roster",
        "flight plan archive",
        "private frequency list",
        "old incident report",
        "unclaimed access badge",
        "route priority stamp"
      ]
    },
    "Production": {
      "First Look": [
        "assembly arms moving without workers",
        "ore hoppers feeding a sealed processor",
        "conveyor belts under harsh yellow lamps",
        "machine floor painted with hazard lines",
        "fabricator banks printing unknown parts",
        "the smell of lubricant and hot ceramic"
      ],
      "Complication": [
        "production cannot stop without financial penalties",
        "a machine is making something illegal",
        "workers sabotage the line for leverage",
        "a trapped crew is inside the machinery",
        "a product batch is biologically contaminated",
        "the output does not match the manifest"
      ],
      "Useful Detail": [
        "industrial exosuit",
        "parts bin",
        "control pendant",
        "safety override key",
        "defective product sample",
        "sealed cargo tag"
      ]
    },
    "Research": {
      "First Look": [
        "observation glass with cracks at the edges",
        "sample vault humming softly",
        "whiteboards full of crossed-out equations",
        "sealed clean room with fogged windows",
        "specimen tanks lit from below",
        "scientists speaking in rehearsed answers"
      ],
      "Complication": [
        "the principal researcher is lying by omission",
        "the experiment changed after last contact",
        "containment depends on a failing generator",
        "a sample is missing but not logged",
        "a discovery has military value",
        "the data proves the patron caused the problem"
      ],
      "Useful Detail": [
        "lab notebook",
        "cryogenic sample",
        "sensor recording",
        "clean-room suit",
        "experiment access code",
        "unpublished survey data"
      ]
    },
    "Security": {
      "First Look": [
        "armory cage with empty racks",
        "holding cells under blue lights",
        "interrogation room with no camera feed",
        "barracks smelling of sweat and solvent",
        "checkpoint barricades made permanent",
        "watch officer studying a threat board"
      ],
      "Complication": [
        "security is split between two loyalties",
        "a prisoner knows too much",
        "weapons were signed out under false names",
        "the official threat is a cover story",
        "a lockdown order is issued remotely",
        "a guard recognizes an old debt"
      ],
      "Useful Detail": [
        "riot shield",
        "detention roster",
        "weapon checkout log",
        "blind camera",
        "coded challenge phrase",
        "confiscated personal item"
      ]
    },
    "Commercial": {
      "First Look": [
        "trade stalls under recycled neon",
        "broker offices with armored windows",
        "cafeteria serving as labor exchange",
        "cargo auction projected on a dirty wall",
        "pawn counter stacked with spacer gear",
        "corporate store charging company scrip"
      ],
      "Complication": [
        "prices shift after a rumor hits",
        "a broker sells the same lead twice",
        "a debt collector interrupts negotiations",
        "the wanted item is counterfeit",
        "a merchant asks for protection instead of money",
        "a public transaction masks a private handoff"
      ],
      "Useful Detail": [
        "market gossip",
        "rare spare part",
        "shipping label",
        "smuggler contact",
        "debt ledger",
        "freshly forged permit"
      ]
    },
    "District Type": [
      "Access",
      "Community",
      "Engineering",
      "Living",
      "Medical",
      "Operations",
      "Production",
      "Research",
      "Security"
    ]
  },
  "Starships": {
    "Ship Type": [
      "frontier scout",
      "subsidized merchant",
      "ore tug",
      "corporate courier",
      "patrol corvette",
      "medical shuttle",
      "research tender",
      "bulk freighter",
      "smuggling cutter",
      "colonial landing craft"
    ],
    "First Look": [
      "scarred hull plates and fresh welds",
      "running lights dimmed to save power",
      "cargo pods arranged asymmetrically",
      "a proud ship name painted over older lettering",
      "exposed sensor mast wrapped in repair tape",
      "clean corporate livery hiding battlefield damage",
      "auxiliary tanks strapped to the spine",
      "docking collar patched from another vessel",
      "engine bells blackened by hard burns",
      "defensive turret tracking too smoothly"
    ],
    "Ship Trouble": [
      "life support scrubbers are near saturation",
      "the ship carries undocumented passengers",
      "fuel reserves are lower than declared",
      "the nav computer refuses one destination",
      "cargo mass does not match the manifest",
      "a crew member is being coerced",
      "the ship is shadowed by a silent transponder",
      "insurance investigators are looking for it",
      "a sealed compartment has its own power draw",
      "the captain owes more than money"
    ],
    "Ship Quirk": [
      "old union stickers on every hatch",
      "a shrine in engineering",
      "AI voice trained on a dead officer",
      "smell of coffee everywhere",
      "manual controls maintained obsessively",
      "patched mascot painted near the airlock",
      "crew uses naval slang incorrectly",
      "every system has a nickname",
      "gravity plates hum in certain corridors",
      "mess table bolted from salvaged armor"
    ]
  },
  "Characters": {
    "First Look": [
      "tired eyes and immaculate uniform",
      "grease-stained coveralls",
      "expensive coat over cheap armor",
      "careful smile that never reaches the eyes",
      "old injury hidden badly",
      "religious token on a pressure suit",
      "corporate badge worn like a weapon",
      "hands shaking from stim use",
      "calm voice in a violent room",
      "helmet visor kept down indoors"
    ],
    "Role": [
      "colonial marshal",
      "company fixer",
      "dock foreman",
      "xenobiologist",
      "belter pilot",
      "union organizer",
      "security lieutenant",
      "smuggler broker",
      "field medic",
      "survey scout",
      "claims lawyer",
      "combat engineer",
      "data archivist",
      "prospector",
      "chaplain"
    ],
    "Goal": [
      "hide a costly mistake",
      "protect family or crew",
      "sell information before it decays",
      "stop the colony from collapsing",
      "escape a contract",
      "complete the mission at any cost",
      "prove a theory",
      "settle an old debt",
      "frame a rival",
      "keep outsiders away from a discovery"
    ],
    "Revealed Aspect": [
      "knows more than they admit",
      "is protecting an enemy",
      "has already betrayed someone",
      "is dying and concealing it",
      "is under surveillance",
      "has a hidden military record",
      "owes the patron money",
      "fears the local environment",
      "is loyal to people not institutions",
      "has evidence but not courage"
    ],
    "Disposition": [
      "helpful but cautious",
      "openly hostile",
      "professionally neutral",
      "desperate for allies",
      "friendly for a price",
      "afraid of being overheard",
      "insulted by outsiders",
      "curious and talkative",
      "polite but obstructive",
      "angry at the wrong target"
    ]
  },
  "Creatures": {
    "Environment": [
      "ventilation shafts",
      "thermal pools",
      "fungal groves",
      "ice tunnels",
      "ore seams",
      "flooded caverns",
      "abandoned habs",
      "storm drains",
      "ship bilges",
      "jungle canopy"
    ],
    "Scale": [
      "insect-sized swarm",
      "small dog-sized pack",
      "human-sized stalker",
      "large predator",
      "vehicle-sized mass",
      "colony organism",
      "microscopic contaminant",
      "parasitic infestation"
    ],
    "Behavior": [
      "observing from cover",
      "protecting a nest",
      "feeding on industrial waste",
      "following heat",
      "mimicking machinery",
      "avoiding bright light",
      "testing boundaries",
      "attacking only the isolated",
      "drawn to sound",
      "responding to electromagnetic signals"
    ],
    "Revealed Aspect": [
      "not native to this world",
      "engineered for a purpose",
      "part of a larger life cycle",
      "carrying valuable compounds",
      "reacts to human stress hormones",
      "uses vents as hunting routes",
      "has been deliberately released",
      "is avoiding something worse",
      "is intelligent enough to bargain indirectly",
      "cannot survive without the facility"
    ]
  },
  "Factions": {
    "Faction Type": [
      "megacorp division",
      "colonial authority",
      "labor union",
      "smuggling ring",
      "military detachment",
      "research consortium",
      "religious community",
      "free trader guild",
      "frontier militia",
      "criminal syndicate"
    ],
    "Influence": [
      "local room-level cell",
      "district authority",
      "settlement power",
      "planetary stakeholder",
      "system-wide actor",
      "sector-level power",
      "shadow network",
      "declining legacy institution"
    ],
    "Project": [
      "control the only safe route",
      "bury liability evidence",
      "monopolize water or air",
      "weaponize a discovery",
      "break a labor movement",
      "smuggle people off-world",
      "force a buyout",
      "secure exclusive salvage rights",
      "trigger a security emergency",
      "extract a dangerous specimen"
    ],
    "Relationship": [
      "uneasy truce",
      "open vendetta",
      "secret partnership",
      "public rivalry private cooperation",
      "patron-client dependency",
      "mutual blackmail",
      "religious or ideological hatred",
      "shared enemy",
      "contractual obligation",
      "family ties across faction lines"
    ],
    "Rumor": [
      "their leader is already dead",
      "they found something beneath the colony",
      "their money comes from an illegal program",
      "they are preparing evacuation lists",
      "they have a private prison",
      "their best asset is a child or dependent",
      "they control the emergency codes",
      "they caused the last disaster",
      "they are being manipulated by an off-world patron",
      "they know how to leave but not who to save"
    ]
  },
  "Derelicts": {
    "Location": [
      "high orbit",
      "lagrange point",
      "ice field",
      "surface crash scar",
      "asteroid cavity",
      "abandoned dock",
      "deep ocean trench",
      "toxic storm basin",
      "mine shaft terminus",
      "gas giant shadow"
    ],
    "Type": [
      "survey ship",
      "ore processor",
      "research station",
      "colony module",
      "military listening post",
      "fuel depot",
      "prison transport",
      "medical frigate",
      "cargo hauler",
      "terraforming platform"
    ],
    "Condition": [
      "power flickers intermittently",
      "partially pressurized",
      "looted but not empty",
      "externally intact internally ruined",
      "sealed by automated quarantine",
      "overgrown by alien biomass",
      "burned from inside",
      "split into accessible sections",
      "occupied by squatters",
      "moving under residual automation"
    ],
    "Outer First Look": [
      "frozen vapor plume",
      "impact scars across the bow",
      "warning strobes still blinking",
      "hull graffiti from later visitors",
      "open cargo bay like a wound",
      "solar panels tracking no star",
      "antenna array folded like broken fingers",
      "lifeboats missing from one side",
      "patched breach with newer metal",
      "strange growth along the seams"
    ],
    "Inner First Look": [
      "floating debris in stale air",
      "emergency lights under ankle-deep water",
      "walls scratched by tools or claws",
      "personal effects left mid-routine",
      "doors welded shut from the wrong side",
      "frost on the inside of helmets",
      "bloodless bodies strapped into chairs",
      "machines continuing a pointless task",
      "air full of glittering dust",
      "soft knocking from deeper inside"
    ]
  },
  "Vaults / Ruins": {
    "Location": [
      "buried under colony foundations",
      "inside a basalt ridge",
      "beneath a dried seabed",
      "within an asteroid core",
      "below a ruined terraformer",
      "in a quarantined jungle zone",
      "under polar ice",
      "behind a collapsed mine face",
      "inside a volcanic tube",
      "beneath an abandoned city block"
    ],
    "Scale": [
      "single sealed chamber",
      "small bunker complex",
      "multi-level facility",
      "city-sized ruin",
      "distributed tunnel network",
      "orbital-linked installation",
      "subsurface labyrinth",
      "machine cathedral"
    ],
    "Purpose": [
      "data archive",
      "biological containment",
      "weapons storage",
      "colony control center",
      "ritual or memorial site",
      "terraforming regulator",
      "AI isolation vault",
      "emergency refuge",
      "genetic library",
      "unknown monitoring station"
    ],
    "Interior Feature": [
      "walls grown rather than built",
      "floor markings that match star charts",
      "sealed pods with internal power",
      "a dry fountain beneath vacuum glass",
      "machinery pulsing like organs",
      "human equipment added later",
      "gravity inconsistent by room",
      "old warning icons in several languages",
      "a chamber that dampens radio signals",
      "a door requiring a living sample"
    ],
    "Peril / Opportunity": [
      "valuable data behind a lethal failsafe",
      "a safe path that destroys evidence",
      "a dormant defense that mistakes intent",
      "a trapped survivor with unreliable memory",
      "a cure stored beside a contaminant",
      "a power source that attracts factions",
      "a shortcut that collapses after use",
      "a map that reveals another threat",
      "an artifact that is also a beacon",
      "an escape route controlled by an enemy"
    ]
  },
  "Location Themes": {
    "Theme Type": [
      "Chaotic",
      "Fortified",
      "Haunted",
      "Infested",
      "Inhabited",
      "Mechanical",
      "Ruined",
      "Sacred",
      "Arid",
      "Chronal",
      "Inferno",
      "Floating",
      "Flooded",
      "Frozen",
      "Lifeform",
      "Overgrown",
      "War Zone",
      "Corporate"
    ],
    "Theme Detail": [
      "authority changes by the hour",
      "defenses face inward as much as outward",
      "old guilt shapes local behavior",
      "small signs of infestation appear before the threat",
      "ordinary life continues around danger",
      "machines obey old priorities",
      "collapse happened in layers",
      "ritual meaning has replaced practical use",
      "water is more valuable than law",
      "events repeat or leave echoes",
      "heat forces timed movement",
      "nothing is anchored securely",
      "every route changes with water levels",
      "cold preserves evidence too well",
      "the place behaves like an organism",
      "nature is reclaiming human systems",
      "old battle lines still matter",
      "profit logic overrides human need"
    ],
    "Sensory Detail": [
      "ozone and hot dust",
      "condensation dripping behind panels",
      "sterile plastic over rot",
      "distant metal impacts",
      "air tasting of copper",
      "warning tones buried in static",
      "old smoke in fabric",
      "chemical flowers under grow lamps",
      "cold biting through gloves",
      "hydraulics sighing like breath"
    ]
  },
  "Missions": {
    "Mission Type": [
      "extract a person",
      "recover cargo",
      "investigate a disappearance",
      "escort a convoy",
      "secure a site",
      "sabotage an operation",
      "negotiate a truce",
      "map a hazard",
      "deliver medicine",
      "prove a crime"
    ],
    "Patron": [
      "company executive",
      "local council",
      "union cell",
      "military officer",
      "worried family",
      "smuggler broker",
      "scientist",
      "colonial marshal",
      "religious leader",
      "anonymous data drop"
    ],
    "Twist": [
      "the patron caused the problem",
      "the target wants to stay hidden",
      "success harms innocents",
      "the reward is access not money",
      "the rival team has the better claim",
      "the threat is a symptom",
      "the official map is false",
      "the job is legal but immoral",
      "the evidence is alive",
      "the mission clock is shorter than stated"
    ],
    "Reward": [
      "fuel allocation",
      "repair parts",
      "legal clearance",
      "local allies",
      "medical treatment",
      "debt forgiveness",
      "exclusive trade rights",
      "hidden coordinates",
      "rare equipment",
      "reputation with a faction"
    ],
    "Heat Result": [
      "security watches future movements",
      "prices rise against the crew",
      "a faction clock advances",
      "a contact goes quiet",
      "official permits are reviewed",
      "a rival spreads a damaging rumor",
      "checkpoint searches intensify",
      "an enemy learns the crew ship ID",
      "a bounty is posted quietly",
      "a patron asks for deniable help"
    ],
    "Danger Clock": [
      "0: ordinary signs of pressure",
      "1: small anomaly or missing detail",
      "2: route, resource, or witness becomes unstable",
      "3: threat demonstrates intent or intelligence",
      "4: faction, environment, or creature cuts off an option",
      "5: direct confrontation, forced choice, or irreversible cost",
      "6: aftermath reveals the next larger problem"
    ]
  },
  "Conflict Architecture": {
    "Stake Anchor": [
      "a person the crew has met",
      "a place that offered shelter",
      "a debt that will come due",
      "a promise made publicly",
      "a scarce resource everyone needs",
      "a moral line a PC does not want to cross",
      "a community that cannot leave",
      "evidence that will ruin someone powerful",
      "a secret tied to the crew past",
      "a future route or refuge"
    ],
    "Opposition Logic": [
      "the antagonist is protecting their own people",
      "the enemy profits from delay",
      "the opposition needs the crew alive for now",
      "the rival believes they are preventing a worse disaster",
      "the faction is obeying a contract with hidden penalties",
      "the antagonist lacks full information",
      "the enemy cruelty is efficient not random",
      "the opposition must act before a public deadline",
      "the villain is trapped by promises to followers",
      "the enemy is trying to erase liability"
    ],
    "Meaningful Choice": [
      "save people now or preserve evidence",
      "honor a contract or protect the vulnerable",
      "move fast and miss clues or investigate and lose time",
      "trust a guilty ally or face a stronger enemy alone",
      "reveal the truth and cause panic or hide it and lose trust",
      "take corporate resources or remain independent",
      "destroy the threat or learn from it",
      "protect the colony or protect the mission",
      "make a public stand or win quietly",
      "rescue one group while abandoning another"
    ],
    "Escalation": [
      "the cost becomes personal",
      "the opposition adapts to the last tactic",
      "a neutral party is forced to choose sides",
      "a deadline becomes visible",
      "resources degrade under pressure",
      "the safe route closes",
      "an ally loyalty is tested",
      "the truth expands the problem",
      "victory in one arena causes trouble in another",
      "the antagonist makes a reasonable offer"
    ]
  },
  "Miscellaneous": {
    "Story Complication": [
      "the clue is real but planted",
      "help arrives with unacceptable terms",
      "an ally is right for the wrong reason",
      "a simple problem exposes a larger system",
      "the obvious enemy is a scapegoat",
      "the clock advances offscreen",
      "the safest plan harms someone unseen",
      "evidence disappears while being protected",
      "a rescue creates a hostage",
      "the map changes because someone moved the goal"
    ],
    "Story Clue": [
      "mismatched timestamps",
      "reused corporate seal",
      "soil where none should be",
      "a voiceprint in background audio",
      "medical dosage inconsistency",
      "manual override residue",
      "missing spare part",
      "radiation shadow",
      "private nickname in formal logs",
      "old route marker"
    ],
    "Item of Narrative Significance": [
      "burned contract",
      "child pressure mask",
      "sealed sample case",
      "broken badge",
      "ship transponder key",
      "old colonial flag",
      "encrypted family recording",
      "bloodless knife",
      "handwritten map",
      "prototype sensor"
    ],
    "Anomaly Effect": [
      "radio messages arrive out of order",
      "organic matter crystallizes briefly",
      "gravity tilts by a few degrees",
      "dreams share common imagery",
      "machines run without power",
      "dead screens show live images",
      "compasses point at a person",
      "shadows lag behind movement",
      "water beads upward",
      "memories surface in unfamiliar voices"
    ],
    "Pay the Price": [
      "lose time",
      "spend supplies",
      "increase threat",
      "increase mystery",
      "mark a faction clock",
      "separate from an ally",
      "damage gear",
      "owe a favor",
      "reveal your presence",
      "trade one danger for another"
    ],
    "Horror Payoff": [
      "the feared thing is real but not the true cause",
      "the rescue target has become part of the danger",
      "the safest room is safe because something is feeding it",
      "the monster follows a rule the crew can exploit",
      "the environment has been warning them all along",
      "the evidence proves negligence, not accident",
      "the creature is less frightening than the decision that made it",
      "the colony can survive only by admitting a hidden crime",
      "the old map is accurate because the ruin is rebuilding itself",
      "the threat recognizes one crew member",
      "the crew has been carrying the clue since scene one",
      "the danger is not entering the colony; it is leaving with the truth"
    ]
  },
  "Plot Engine": {
    "Plot Target": [
      "a person with divided loyalties",
      "a vulnerable worker group",
      "a hidden object in transit",
      "an abstract right or legal claim",
      "a failing colony system",
      "a dangerous scientific truth",
      "a trade monopoly",
      "a route through hostile space",
      "a local taboo or tradition",
      "a buried corporate liability",
      "a missing expedition record",
      "an emergency evacuation list",
      "a hostage supply chain",
      "an illegal specimen",
      "a disputed water or air contract",
      "a suppressed casualty report",
      "a prototype under field testing",
      "a witness whose memory has gaps",
      "a settlement charter",
      "a faction's claim to legitimacy"
    ],
    "Plot Method": [
      "blackmail through falsified records",
      "sabotage disguised as maintenance failure",
      "legal seizure under emergency authority",
      "deliberate ration manipulation",
      "staged rescue to gain trust",
      "planted evidence against a useful scapegoat",
      "controlled leak of partial truth",
      "use of debt markers and contract penalties",
      "manufactured panic to justify force",
      "quiet replacement of key personnel",
      "weaponized quarantine procedure",
      "relocation order that separates witnesses",
      "false distress call",
      "disinformation through local rumor channels",
      "contamination of a route or resource",
      "tampered scout report",
      "forged evacuation priority list",
      "predator release framed as natural migration",
      "memory-editing or sedation hidden as medical care",
      "remote system lockout during negotiation"
    ],
    "Plot Reveals": [
      "the patron is using the crew as deniable pressure",
      "the villain is protecting someone from a worse faction",
      "the disaster was predicted and ignored",
      "the official enemy is a decoy",
      "the evidence proves several parties are guilty",
      "the victim arranged part of their own disappearance",
      "the route is dangerous because it is hiding something",
      "a minor NPC has the decisive evidence",
      "the cure or fix creates a new dependency",
      "the local authority knows but lacks leverage",
      "the apparent monster is following learned behavior",
      "the cargo is valuable because of who wants it destroyed",
      "the colony cannot survive the truth becoming public",
      "the threat began as a cost-saving measure",
      "the map was edited after the last transmission",
      "the real antagonist is a contract clause",
      "the specimen is a warning system, not a weapon",
      "the missing crew chose silence to protect others",
      "the settlement's success depends on an atrocity",
      "the rescue mission is really a containment mission"
    ],
    "Scene Driver": [
      "deadline before a storm, launch, lockdown, or vote",
      "resource drain that worsens every scene",
      "rival team moving in parallel",
      "NPC loyalty under stress",
      "a clue that can be lost or contaminated",
      "a safe place becoming unsafe",
      "a moral debt being called in",
      "communication lag or blackout",
      "crew reputation changing local reactions",
      "heat from a previous mission arrives early",
      "life support margin shrinking by the hour",
      "an enemy testing responses",
      "a disease clock with unclear symptoms",
      "a public crowd demanding an answer",
      "a legal window closing"
    ]
  },
  "Danger Situations": {
    "Industrial Hazards": [
      "pressure door cycling while someone is trapped between locks",
      "coolant fog hiding a floor-level breach",
      "reactor vibration changing from background noise to rhythm",
      "ore conveyor dragging cargo toward a crusher",
      "static discharge arcing across wet decking",
      "toxic washdown system triggering without warning",
      "autonomous loader misidentifying people as cargo",
      "magnetic crane dropping scrap in irregular intervals",
      "emergency shutters dividing the group",
      "air scrubbers spreading rather than filtering the contaminant",
      "fuel vapor pooling near a sparking relay",
      "damaged gravity plates creating fall zones",
      "maintenance bot following obsolete lethal instructions",
      "pressure gauges showing impossible values",
      "a machine room too loud for shouted warnings"
    ],
    "Environmental Dangers": [
      "storm front cuts off the return route",
      "thin ice or crust hides a deep void",
      "local pollen clogs filters and changes voices",
      "heat shimmer conceals moving shapes",
      "purple aurora distorts depth perception",
      "regenerating soil swallows tracks too quickly",
      "microtremors turn quiet movement into noise",
      "corrosive mist eats exposed seals",
      "flash flood fills the lowest passage first",
      "predators use wind or machinery to mask approach",
      "dust carries a mild hallucinogen",
      "surface becomes reflective at night and ruins navigation",
      "gravity flux turns slopes into traps",
      "fungal mats exhale when stepped on",
      "the safest landmark moves with the tide or storm"
    ],
    "Space and Vacuum Dangers": [
      "slow decompression too quiet for immediate panic",
      "tether line fraying under unseen stress",
      "maneuvering thrusters firing on a damaged schedule",
      "cargo pod drifting toward a gravity well",
      "radiation shadow shows something large nearby",
      "airlock handshake failing after the outer door opens",
      "ice crystals obscuring suit cameras",
      "silent object matching speed with the ship",
      "debris field rotating faster than predicted",
      "rescue beacon repeating in a dead crew member's voice",
      "hull patch flexing with every pressure cycle",
      "navigation update contradicting the visual field",
      "a suit alarm belongs to someone not on the EVA roster",
      "comet venting jets that change the landing geometry",
      "asteroid fragments carrying active transponders"
    ],
    "Social Dangers": [
      "a crowd deciding whether the crew is useful or guilty",
      "a frightened witness changing their story under pressure",
      "security asking questions they already know the answers to",
      "a broker selling silence by the minute",
      "a local custom that makes refusal dangerous",
      "an authority figure demanding public loyalty",
      "a desperate parent exposing a hidden route",
      "a rival offering the same deal first",
      "a faction using the crew to test an enemy",
      "a room going quiet when one name is mentioned",
      "a hostage negotiation framed as a contract dispute",
      "a confession that implicates an ally",
      "a rumor that makes peaceful entry impossible",
      "a lawful order that would doom innocents",
      "a beloved local figure lying for understandable reasons"
    ]
  },
  "Fear and Dread": {
    "Fear Trigger": [
      "being watched by something unseen",
      "contamination that spreads through ordinary contact",
      "isolation from crew, ship, or comms",
      "darkness that behaves like a physical pressure",
      "confinement with shrinking options",
      "familiar people acting subtly wrong",
      "evidence of a predator learning",
      "dead systems moving as if alive",
      "a safe routine violated once, then twice",
      "a sound that stops when noticed",
      "the loss of memory, name, or identity",
      "body transformation too slow to deny",
      "authority figures more frightened than civilians",
      "the realization that rescue cannot arrive in time",
      "a place that remembers earlier visitors",
      "an evacuation route that becomes a choice of who deserves to leave",
      "a harmless biological trace becoming meaningful later",
      "a machine predicting events it should not know",
      "a corpse or wreck arranged to communicate",
      "the crew's own voices coming from ahead"
    ],
    "Dread Technique": [
      "show the aftermath before the cause",
      "give partial information that supports two bad theories",
      "repeat one sensory detail with increasing wrongness",
      "let an NPC panic at something the crew cannot yet see",
      "make the safe route require a moral cost",
      "withhold the monster but reveal its intelligence",
      "make technology fail in a consistent, meaningful pattern",
      "introduce one impossible detail in an ordinary scene",
      "allow a short calm beat before the next escalation",
      "make the environment respond to the crew's actions",
      "make the threat avoid direct confrontation until it knows enough",
      "turn a useful tool into a source of vulnerability",
      "force quiet choices instead of open combat",
      "make escape possible but costly",
      "make the truth useful and destabilizing",
      "show an expert losing confidence",
      "let the first success create a worse question",
      "turn a map, log, or checklist into a countdown",
      "reveal that the crew has been following the threat's preferred path",
      "let the scene answer a question no one asked"
    ],
    "Uncanny Detail": [
      "a person smiles half a second late",
      "a recorded voice answers a question it never heard",
      "a corpse is warm in only one hand",
      "the same scratch mark appears on both sides of a sealed door",
      "children's drawings show tomorrow's event",
      "a machine uses a human nickname no one entered",
      "a reflection includes one extra figure",
      "a familiar room is one meter too long",
      "a trusted ally uses the wrong childhood memory",
      "an animal moves like it is wearing a shape",
      "a helmet camera shows breathing condensation from an empty suit",
      "a map labels a location with the crew's ship name",
      "a wound contains clean machine parts",
      "footsteps match the listener's pace exactly",
      "a dead comm channel whispers only when ignored",
      "a warning sign uses a future date",
      "a child's toy repeats a security code",
      "a pressure suit stands upright with no body inside",
      "the same NPC arrives twice by different routes",
      "a familiar logo is printed backward on every surface"
    ],
    "Revelation Timing": [
      "hint now, confirm two scenes later",
      "reveal the cost before the cause",
      "show a small contradiction in a trusted record",
      "let a panicked NPC name the wrong threat",
      "make the first explanation comforting but false",
      "make the second explanation true but incomplete",
      "reveal the monster's rule before its form",
      "reveal the human choice that enabled the horror",
      "tie the reveal to a resource running out",
      "let the crew choose whether to open the final proof",
      "show a witness who survived by misunderstanding events",
      "reveal a faction's guilt through routine paperwork",
      "make the last clue auditory rather than visual",
      "confirm the worst theory only after the crew has acted against it",
      "let the enemy reveal useful truth as a bargaining tactic"
    ],
    "Safety-Aware Horror Prompt": [
      "keep harm implied and focus on suspense",
      "use environmental dread rather than graphic detail",
      "frame terror through choices and consequences",
      "let players decide how close to inspect the disturbing evidence",
      "make panic tactical, not punitive",
      "use NPC fear to signal danger without forcing player emotion",
      "offer a visible exit at a cost",
      "keep the threat coherent so fear feels fair",
      "avoid shock for its own sake; reveal information that matters",
      "follow intense scenes with a chance to regroup",
      "aim fear at uncertainty, isolation, and stakes rather than helplessness",
      "keep body horror optional and abstract",
      "make disturbing clues skippable without blocking progress",
      "use veiled descriptions when a result could become graphic",
      "give player characters meaningful agency even in a doomed situation"
    ]
  },
  "Colonies and Expeditions": {
    "Colony Pressure": [
      "integrity damage in an essential system",
      "morale falling after a failed mission",
      "raw materials depleted by emergency repairs",
      "research promising a solution but requiring risk",
      "enemy activity increasing near a sector border",
      "scout report contradicting orbital scans",
      "settlers demanding action before evidence is complete",
      "food production threatened by alien contamination",
      "construction delayed by missing parts",
      "medical capacity overwhelmed by unknown symptoms",
      "a new building draws unwanted attention",
      "an evacuation plan includes too few seats",
      "a supply shuttle missed its automated window",
      "maintenance debt from earlier shortcuts comes due",
      "a leadership dispute splits the work crews"
    ],
    "Expedition Objective": [
      "investigate a ruin without disturbing active systems",
      "recover a scout team before the storm closes",
      "sample a lifeform without triggering territorial behavior",
      "map a safe corridor for colony expansion",
      "destroy a nest or transmitter near the perimeter",
      "escort engineers to a damaged remote station",
      "locate raw materials needed for repairs",
      "confirm whether an enemy sector is occupied",
      "retrieve a cargo pod from unstable terrain",
      "test a theory before the colony commits resources",
      "repair a beacon that may attract help or enemies",
      "find why drones vanish beyond a ridge",
      "recover a rover before its logs are overwritten",
      "seal an opening discovered under new construction",
      "verify a friendly contact who arrived without warning"
    ],
    "Battlefield Condition": [
      "low visibility with intermittent sensor ghosts",
      "unstable footing or partial gravity",
      "hard cover that also blocks retreat",
      "hazardous pools, vents, or electrical arcs",
      "civilian presence limits firepower",
      "moving machinery changes lanes of attack",
      "enemy has high ground but poor mobility",
      "valuable samples can be destroyed by stray shots",
      "reinforcements arrive if alarms persist",
      "the terrain itself attracts predators",
      "the safest cover is contaminated",
      "line of sight changes with rotating shadows or storms",
      "a resource objective is heavier than expected",
      "sound discipline matters more than speed",
      "heat signatures reveal both sides to something else"
    ],
    "Post-Mission Find": [
      "alien artifact with an obvious use and hidden cost",
      "data fragment pointing to a larger pattern",
      "usable construction materials",
      "bio-sample unlocking a research theory",
      "survivor with damaged memory",
      "old colony marker from an unknown faction",
      "enemy equipment adapted to local conditions",
      "map of a sealed sector",
      "medical compound that treats one symptom",
      "supply cache with a claim tag",
      "recording that changes mission priorities",
      "tool that makes the next expedition safer",
      "partial coordinates to a safer landing zone",
      "organism that reacts to settlement power systems",
      "proof that the colony is not the first settlement here"
    ]
  }
};
